[package]
name = "dir-sorter"
version = "0.1.0"
edition = "2021"
authors = ["Muhammad Usman <github.com/usmandevstuff>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.27.1"
rfd = "0.14.1"
